apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kuhp-analyzer-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "500m"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/kuhp-analyzer-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "https://BACKEND_SERVICE_URL"
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"